name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'Naveenraj M'

inputs: 
  spec_file:
    description: 'path to the spec file'
    required: true
    default: '*.spec'                     #Any spec file in top
  target:
    description: 'mock configname'
    required: true
  additional_repos:
    description: 'A list of additional repositories to enable'
    required: false

outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_path:
    description: 'path to RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_name:
    description: 'name of RPM file'
  rpm_content_type:
    description: 'Content-type for Upload'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Build Dockerfile
      run: |
        docker build . --tag=mockbuilder:latest
    - name: Run Container
      run: |
        docker run mockbuilder:latest -v ${{ github.workspace }}:/github/workspace --privileged
branding:
  icon: 'package'
  color: 'red'

  
